apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argocd
resources:
  # Bitnami
  - ../base/bitnami
  # Sealed Secrets
  - ../../env/brain12
  # ArgoCD
  - ../base/argocd
  # Persitent Storage
  - storage/brain12-persistent-storage.yaml
patchesStrategicMerge:
  - argocd/planckster-kubeflow-core-application.yaml
  - argocd/planckster-kubeflow-core-namespaces-application.yaml
  - argocd/planckster-kubeflow-components-namespaces-application.yaml
  - argocd/planckster-kubeflow-components-application.yaml