apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # sealed secrets to be used in the cluster
  - dex/dex_config_secret_sealed.json
  - dex/custom_theme/custom_theme_secret_sealed.json
  - oidc-authservice/oidc-authservice-client-parameters-secret-sealed.json
  - oidc-authservice/oidc-authservice-parameters-secret-sealed.json
  # - user-namespace/profile-instance.yaml
  - centraldashboard/centraldashboard-parameters-secret-sealed.json