apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: brain12-persistent-storage-class
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  pvDir: /kubeflow_volumes/
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - brain12