apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: planckster-kubeflow-components-namespaces-application
spec:
  source:
    path: deployment/kubeflow_components_namespaces/staging