apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # ArgoCD v2.7.5
  # -> taken from https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.5/manifests/install.yaml
  - namespace.yaml
  - install.yaml
  # Applications
  - planckster-secrets-application.yaml
  - planckster-kubeflow-core-application.yaml
  - planckster-kubeflow-core-namespaces-application.yaml
  - planckster-kubeflow-components-application.yaml
  - planckster-kubeflow-components-namespaces-application.yaml
  - planckster-data-baits-examples-application.yaml
  - redeployer-application.yaml
