apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: planckster-kubeflow-components-application
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: ./ # to be changed in environments
    repoURL: 'https://github.com/mmazurekgda/inferring-kubeflow-manifests'
    targetRevision: v0.2.0
  sources: []
  project: ''
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
